#!/usr/bin/env python3
"""Generate seed.sql for the SuperYou demo D1 database.

Reads the real superyou.in Shopify catalogue (products.json) and generates
Shopify-shaped mock data: ~120 customers, ~250 orders with line items and
ClickPost-style fulfillments across realistic statuses.

Usage: python3 gen_seed.py ../../../../.firecrawl/superyou-products.json > seed.sql
"""

import json
import random
import re
import sys
from datetime import datetime, timedelta

random.seed(42)

FIRST_NAMES = [
    "Aarav", "Vivaan", "Aditya", "Arjun", "Reyansh", "Sai", "Krishna",
    "Ishaan", "Rohan", "Kabir", "Ananya", "Diya", "Saanvi", "Aadhya",
    "Kiara", "Myra", "Anika", "Navya", "Priya", "Riya", "Shivam",
    "Keshav", "Vishesh", "Aaron", "Neha", "Pooja", "Rahul", "Simran",
]
LAST_NAMES = [
    "Sharma", "Verma", "Patel", "Reddy", "Nair", "Iyer", "Gupta",
    "Singh", "Kumar", "Das", "Chopra", "Mehta", "Joshi", "Kulkarni",
    "Banerjee", "Mukherjee", "Agarwal", "Malhotra", "Bhat", "Rao",
]
CITIES = [
    "Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Chennai", "Pune",
    "Kolkata", "Ahmedabad", "Jaipur", "Lucknow", "Gurugram", "Noida",
    "Indore", "Kochi", "Chandigarh",
]
COURIERS = ["Delhivery", "BlueDart", "Ecom Express", "XpressBees", "DTDC"]

# (shipment_status, fulfillment.status, weight) - realistic distribution
SHIPMENT_STATES = [
    ("delivered", "success", 55),
    ("in_transit", "open", 15),
    ("out_for_delivery", "open", 8),
    ("picked_up", "open", 6),
    ("label_created", "pending", 5),
    ("attempted_delivery", "open", 6),
    ("failure", "failure", 5),
]

CHECKPOINTS = {
    "label_created": "Shipping label created at SuperYou warehouse, Bhiwandi",
    "picked_up": "Shipment picked up by {courier} from Bhiwandi fulfillment center",
    "in_transit": "Departed {hub} sorting hub",
    "out_for_delivery": "Out for delivery with {courier} delivery associate, {city}",
    "attempted_delivery": "Delivery attempted - customer unavailable, will retry next working day",
    "delivered": "Delivered - received by customer, {city}",
    "failure": "Delivery failed - address unserviceable, return to origin initiated",
}
HUBS = ["Bhiwandi", "Nagpur", "Delhi NCR", "Hosur", "Zirakpur"]


def esc(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def strip_html(html):
    text = re.sub(r"<[^>]+>", " ", html or "")
    return re.sub(r"\s+", " ", text).strip()[:600]


def pick_weighted(states):
    total = sum(w for _, _, w in states)
    r = random.uniform(0, total)
    acc = 0
    for status, fstatus, w in states:
        acc += w
        if r <= acc:
            return status, fstatus
    return states[0][0], states[0][1]


def main():
    products_path = sys.argv[1]
    with open(products_path) as f:
        catalogue = json.load(f)["products"]

    now = datetime(2026, 7, 4, 12, 0, 0)
    out = []
    out.append("-- Generated by gen_seed.py - do not edit by hand")
    out.append("DELETE FROM fulfillments; DELETE FROM order_line_items;")
    out.append("DELETE FROM orders; DELETE FROM customers; DELETE FROM products;")

    products = []
    for p in catalogue:
        variant = p["variants"][0]
        products.append(
            {
                "id": p["id"],
                "handle": p["handle"],
                "title": p["title"],
                "type": p.get("product_type") or "Protein",
                "price": float(variant["price"]),
                "grams": variant.get("grams") or 0,
                "body": strip_html(p.get("body_html", "")),
            }
        )
    for p in products:
        out.append(
            "INSERT INTO products (id, handle, title, product_type, price, grams, body_text) "
            f"VALUES ({p['id']}, {esc(p['handle'])}, {esc(p['title'])}, {esc(p['type'])}, "
            f"{p['price']}, {p['grams']}, {esc(p['body'])});"
        )

    customers = []
    for i in range(1, 121):
        fn = random.choice(FIRST_NAMES)
        ln = random.choice(LAST_NAMES)
        phone = f"+91{random.choice('6789')}{random.randint(100000000, 999999999)}"
        customers.append(
            {"id": i, "fn": fn, "ln": ln, "phone": phone, "city": random.choice(CITIES)}
        )

    order_rows, li_rows, ful_rows = [], [], []
    order_counts = {}
    order_num = 10001
    for oid in range(1, 251):
        c = random.choice(customers)
        order_counts[c["id"]] = order_counts.get(c["id"], 0) + 1
        created = now - timedelta(days=random.randint(0, 45), hours=random.randint(0, 23))
        items = random.sample(products, k=random.choice([1, 1, 1, 2, 2, 3]))
        total = 0.0
        for it in items:
            qty = random.choice([1, 1, 1, 2])
            total += it["price"] * qty
            li_rows.append((oid, it["id"], it["title"], qty, it["price"]))

        cancelled = random.random() < 0.03
        if cancelled:
            order_rows.append(
                (oid, f"#SY{order_num}", c, "refunded", None, total, created, created + timedelta(hours=2))
            )
        else:
            ship_status, ful_status = pick_weighted(SHIPMENT_STATES)
            f_status = (
                "fulfilled" if ship_status == "delivered" else ("partial" if ful_status == "open" else None)
            )
            order_rows.append(
                (oid, f"#SY{order_num}", c, "paid", f_status, total, created, None)
            )
            courier = random.choice(COURIERS)
            checkpoint = CHECKPOINTS[ship_status].format(
                courier=courier, city=c["city"], hub=random.choice(HUBS)
            )
            eta = created + timedelta(days=random.randint(2, 6))
            scan_at = min(now, created + timedelta(days=random.randint(0, 4)))
            ful_rows.append(
                (oid, ful_status, courier, f"{courier[:2].upper()}{random.randint(10**9, 10**10 - 1)}",
                 ship_status, eta, checkpoint, scan_at)
            )
        order_num += 1

    for cid, cnt in sorted(order_counts.items()):
        pass  # orders_count updated below per customer insert

    for c in customers:
        out.append(
            "INSERT INTO customers (id, first_name, last_name, phone, default_city, orders_count) "
            f"VALUES ({c['id']}, {esc(c['fn'])}, {esc(c['ln'])}, {esc(c['phone'])}, "
            f"{esc(c['city'])}, {order_counts.get(c['id'], 0)});"
        )

    for oid, onum, c, fin, ful, total, created, cancelled_at in order_rows:
        out.append(
            "INSERT INTO orders (id, order_number, customer_id, phone, financial_status, "
            "fulfillment_status, total_price, shipping_city, created_at, cancelled_at) "
            f"VALUES ({oid}, {esc(onum)}, {c['id']}, {esc(c['phone'])}, {esc(fin)}, {esc(ful)}, "
            f"{round(total, 2)}, {esc(c['city'])}, {esc(created.isoformat())}, "
            f"{esc(cancelled_at.isoformat()) if cancelled_at else 'NULL'});"
        )

    for oid, pid, title, qty, price in li_rows:
        out.append(
            "INSERT INTO order_line_items (order_id, product_id, title, quantity, price) "
            f"VALUES ({oid}, {pid}, {esc(title)}, {qty}, {price});"
        )

    for oid, status, courier, awb, ship, eta, checkpoint, scan_at in ful_rows:
        out.append(
            "INSERT INTO fulfillments (order_id, status, tracking_company, tracking_number, "
            "shipment_status, estimated_delivery_at, last_checkpoint, last_checkpoint_at) "
            f"VALUES ({oid}, {esc(status)}, {esc(courier)}, {esc(awb)}, {esc(ship)}, "
            f"{esc(eta.isoformat())}, {esc(checkpoint)}, {esc(scan_at.isoformat())});"
        )

    print("\n".join(out))


if __name__ == "__main__":
    main()
